### ISSUE TITLE
markdown parsed from raml does not contain all possible information like query parameters and examples

### ISSUE THREAD

**Issue by Nightpanda** [raml2html/markdown-theme#4]
There seems to be something wrong with the way the raml file gets parsed to markdown. The description gets parsed, but additional information relevant to the path like queryParameters and examples are not getting parsed into the markdown file.

This can be seen here in the repository by comparing the markdown example and the raml file it is based on so I am not providing my own example.

**Comment by kevinrenskers** [comment]
It's not a bug, it's simply not part of the template to keep the output super simple. 

If you want to show more information, you could simply clone or fork this repo, alter the templates and release it as your own theme on NPM.

**Comment by JemarJones** [comment]
@kevinrenskers Could this be made clear in the documentation? I was also under the impression that all the important information would be transferred as well.

**Comment by kevinrenskers** [comment]
Good idea, could you send a PR with the changes?
